### ISSUE TITLE
Creating a guide and tutorial for putting the Broadcast Box project online with domain and SSL.

### ISSUE THREAD

**Issue by aloproducao** [Glimesh/broadcast-box#10]
Hello,

As a user of the Broadcast Box project, we would like to have a step-by-step guide and a video tutorial to assist the community in putting the project online with a custom domain and an SSL certificate. This would allow new users to become interested in the fantastic project which can produce great tools for the community.
In summary, creating a guide and tutorial on how to put the Broadcast Box project online with a domain and SSL would be extremely beneficial for the community.
Please consider creating these resources and I am willing to help in any way.

**Comment by Sean-Der** [comment]
Hi @aloproducao 

I think this is really important actually! Sorry I have been slow responding, it is a busy time in my life (having another baby soon).

Would you interested in helping with this? The way I host things is with Caddy + Digital Ocean. If you write a official tutorial I would love to link to it in the README.

thanks

**Comment by aloproducao** [comment]
Hi! Congratulations on the arrival of another member to your family! I am very happy to hear about it. I already have two, I know how complicated and wonderful it is.

Definitely, it would be a pleasure to help with the tutorial. I created some scripts that can help implement the code in an easier and more efficient way. I will dedicate myself to writing the tutorial as soon as possible and send it to you for review and sharing in the README.

I am eager to collaborate and help in the best way possible.

**Comment by aloproducao** [comment]
I am engaged in documentation work and have a question. Specifically, I need to know how to transmit signals from an external encoder not associated with OBS. I discovered a repository that may provide a solution, and I am in the process of creating a step-by-step guide to using the Glimesh broadcast. Would you be able to provide assistance with this matter?

Link repo: [](https://github.com/pipe/whipi) @Sean-Der

**Comment by thesalmonification** [comment]
Hi! I'm trying to create an instance of broadcast box for a school project. Is there any update to the documentation for domains/TLS?  I don't have much experience with this tech, but my initial instinct is that you're using a Caddy to create reverse proxy for broadcast box (thereby serving the website as HTTPS but without changing the HTTP Go code). Am I on the right path?

**Comment by Sean-Der** [comment]
I added a guide + tooling to make this easier!

### Network Test on Startup

Broadcast Box will now make sure that connectivity is possible on startup. If your server is configured incorrectly it will tell you. You can read more about it [here](https://github.com/Glimesh/broadcast-box?tab=readme-ov-file#network-test-on-start) this will hopefully help people debugging more.

### Docker Compose with HTTPs

I have updated the docker-compose to use Caddy. All you need to do is set `URL` and everything will just work! https://github.com/Glimesh/broadcast-box?tab=readme-ov-file#docker-compose

----

@aloproducao if you get a chance check it out and tell me what you think :)
