### ISSUE TITLE
My obs lacks WISH stream option

### ISSUE THREAD

**Issue by ian-kelling** [Glimesh/broadcast-box#107]
I built obs on GNU/Linux with -DENABLE_WEBRTC=ON, but then  in the stream options, I don't see WISH like in the screenshot in the readme of this project. Am I missing something? I'm using the current master of obs commit 3a1035576eb6a7c60c1757b3498d97da5d7bfb3b

**Comment by ian-kelling** [comment]
typo: the title should say WHIP not WISH.

**Comment by ian-kelling** [comment]
I figured out why. I ran obs --verbose | grep webrtc and I see this:

error: os_dlopen(../../obs-plugins/64bit/obs-webrtc.so->../../obs-plugins/64bit/obs-webrtc.so): libdatachannel.so.0.20: cannot open shared object file: No such file or directory

fixed with

```
cd $HOME/obs-studio-portable/bin/64bit
cp -a /usr/local/lib/libdatachannel.so* ../../obs-plugins/64bit
```

**Comment by aMytho** [comment]
For those who downloaded the ubuntu/debian PPA and don't see the WHIP service, try the flatpak. The ubuntu build doesn't have that option as of v31. The flatpak does.

https://obsproject.com/kb/whip-streaming-guide
