### ISSUE TITLE
Wrong SDP response status code

### ISSUE THREAD

**Issue by longern** [Glimesh/broadcast-box#11]
According to the [standard](https://www.ietf.org/archive/id/draft-ietf-wish-whip-01.html#section-3), the status code of SDP response should be 201 Created, while in this repo it is currently 200 instead.

**Comment by mpisat** [comment]
w.WriteHeader(http.StatusCreated)
can remedy this problem. Needs to be inserted before 
	fmt.Fprint(w, peerConnection.LocalDescription().SDP)
in whipHandler func.
