### ISSUE TITLE
Spaces in bearer token isn't properly sanitized when loading on web

### ISSUE THREAD

**Issue by wolfcomp** [Glimesh/broadcast-box#136]
When putting a token into the web browser, all spaces are converted over to `%20` while what is received from OBS doesn't contain this sanitization. This causes a flow break when trying to load the stream, as you aren't allowed to send non-sanitized spaces in a web browser.
![img](https://screenshots.wildwolf.dev/msedge_6a18808583.png)

**Comment by wolfcomp** [comment]
If I'm looking at the code correctly, there is no protection against setting protected HTTP characters in the request and should be added to this line of code https://github.com/Glimesh/broadcast-box/blob/main/main.go#L81 this should include both
characters needing https://datatracker.ietf.org/doc/html/rfc3986#section-2.1 and the following characters https://datatracker.ietf.org/doc/html/rfc3986#section-2.2 on a blacklist

**Comment by Sean-Der** [comment]
Thanks for digging on this @wolfcomp!

Do you have the time to add URL sanitizers to WHIP+WHEP requests?

**Comment by wolfcomp** [comment]
I don't know the functions in the go language, so I won't be of help there. I can however compile a regex string for all the characters

**Comment by dilllxd** [comment]
I attempted a fix, not sure if it's the best way of doing it but it did work when tested locally. Hopefully it should help in the end though :)
