### ISSUE TITLE
Support libp2p

### ISSUE THREAD

**Issue by Pantyhose-X** [Glimesh/broadcast-box#14]
[libp2p](https://libp2p.io/) is a modular system of protocols,
[libp2p](https://libp2p.io/) powers many distributed and peer-to-peer systems. Developers can use libp2p as a networking layer to build peer-to-peer applications.

Why [libp2p](https://libp2p.io/)? 
There are several reasons to consider using libp2p as a networking layer to create a robust P2P application:

- Modularity: libp2p is designed to be modular, allowing developers to mix and match different components to meet the needs of their particular application. This makes it easy to customize the networking stack to fit the specific requirements of any P2P application.

- Extensive transport configurability: libp2p provides a set of specifications that can be adapted to support various [transport protocols](https://docs.libp2p.io/concepts/transports/overview), allowing libp2p applications to operate in various runtime and networking environments as the wealth of transport protocol choices makes it possible to use libp2p in a variety of scenarios.

- Versatility: In addition to supporting a wide range of transports, libp2p offers a range of discovery mechanisms, data storage and retrieval patterns, and is also [implemented in many programming languages](https://libp2p.io/implementations/), providing developers with great flexibility when building P2P applications.

- Security: libp2p includes [several security features](https://docs.libp2p.io/concepts/security/security-considerations), such as peer identity verification using public key cryptography and [encrypted communication](https://docs.libp2p.io/concepts/secure-comm/overview) between peers using modern cryptographic algorithms.

- Robustness: libp2p is a robust and reliable networking protocol that is designed to withstand stress, disturbance, and change. Its features and design choices ensure that it is able to function effectively and efficiently in a wide range of environments, and it is able to recover quickly from disruptions or failures. It also offers protection against network attacks through the use of [mitigation techniques](https://docs.libp2p.io/concepts/security/dos-mitigation).

- Resiliency: P2P networks are often more resilient than traditional client-server networks, as there is no single point of failure. libp2p includes features such as [peer discovery](https://docs.libp2p.io/concepts/discovery/overview) and [content routing](https://docs.libp2p.io/concepts/routing/overview) that help to ensure that the network remains available and accessible even if some peers are offline or unreachable.

- Efficiency: P2P networks can be more efficient in resource utilization, as data is distributed across multiple peers rather than stored on a central server. libp2p includes various storage and retrieval patterns that allow developers to distribute data efficiently across the network, making it possible to store and retrieve data in a cost-effective and scalable way.

- Piercing NAT Barriers: libp2p is equipped with capabilities for [NAT traversal](https://docs.libp2p.io/concepts/nat/overview), which allows P2P communication between peers even when they are behind NAT devices or firewalls. This helps to maintain the connectivity of the network and ensure that it remains accessible despite the presence of these obstacles.

- Message Distribution and Dissemination: One such pattern libp2p uses is [publish/subscribe (pubsub)](https://docs.libp2p.io/concepts/pubsub/overview), which allows a sender (publisher) to send a message to multiple recipients (subscribers) without the publisher having to know who the subscribers are. libp2p implements pubsub through the use of protocols like [gossipsub](https://docs.libp2p.io/concepts/pubsub/gossipsub), providing developers with a flexible and efficient means of exchanging data and messages within their P2P applications.

- Interoperability: libp2p implementations in different programming languages and libp2p releases across versions are designed to be interoperable with one another. This enables applications /from different language ecosystems to communicate seamlessly. This helps to promote a healthy, interconnected ecosystem of P2P applications.

- Decentralization: One of the main advantages of P2P networks is their decentralized nature, allowing them to operate without a central authority. libp2p is designed to facilitate decentralized communication between peers, making it possible to build P2P applications resistant to censorship and more resilient in the face of network disruptions.

**Comment by Sean-Der** [comment]
Hi @Pantyhose-X 

Sorry I didn't respond to this sooner. I just found more time to work on Broadcast Box again.

This repo exists to demonstrate [WHIP](https://datatracker.ietf.org/doc/draft-ietf-wish-whip/) and [WHEP](https://datatracker.ietf.org/doc/html/draft-murillo-whep-02). To keep it small/understandable we won't be expanding it to support other protocols.

I am a huge fan of libp2p (did some work with it for Pion). If there is anything I can do to help with other libp2p + video projects I am available. It just doesn't make sense to add libp2p to broadcast-box itself.
