### ISSUE TITLE
How to setup it to stream worldwide?

### ISSUE THREAD

**Issue by devintly** [Glimesh/broadcast-box#16]
Hello, i'm on windows server 2022 vds rightnow, without virtualizaton, so how can i deploy this tool to be able to connect from every part of planet without using docker? It only starts localhost, no matter development or production enviroment, thanks in advance!

**Comment by makindotcc** [comment]
How do you start broadcast-box server? Can you show logs?
```sh
APP_ENV=production go run .
```
By default following command should bind server on every network interface. You probably need to configure firewall somehow, but unfortunately I've never used windows server.

**Comment by Sean-Der** [comment]
Hi @devintly 

I have updated the docker-compose to use Caddy. All you need to do is set `URL` and everything will just work! https://github.com/Glimesh/broadcast-box?tab=readme-ov-file#docker-compose

I would suggest using Linux instead of Windows if possible.

thanks
