### ISSUE TITLE
Where to download OBS with WebRTC Support/No WebRTC Option in OBS

### ISSUE THREAD

**Issue by alirgion** [Glimesh/broadcast-box#20]
Hi,
I can't find an option to use WebRTC as my output in OBS. I read the readme multiple times and can't find any special steps required to unlock this option. If however there is such a step and I have missed it then I'm sorry. 
What should I do?

**Comment by Sean-Der** [comment]
Hey @alirgion!

Download it from this page https://github.com/obsproject/obs-studio/actions/runs/5227109208

WebRTC will be available starting in v30

**Comment by Phrynobatrachus** [comment]
I was able to get things working on Ubuntu by building both libdatachannel and obs from latest master, thanks to this comment and the few replies above it:

https://github.com/obsproject/obs-studio/pull/7926#issuecomment-1509897377

The patching step can be skipped.

**Comment by Gol-D-Ace** [comment]
Just letting people know that the OBS 30 Beta includes WHIP.

For Ubuntu if you don't want to build yourself you can use the Flatpak.

Building on the ppa with whip is currently not possible because of the missing libdatachannel package.

**Comment by Sean-Der** [comment]
WHIP is available in OBS v30! If you are still having issues reach out.

Thanks for trying Broadcast Box :)
