### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by spkpal** [Glimesh/broadcast-box#22]
Can anyone help me please

i have no idea on how to use broadcast Box at all

please help me

**Comment by Sean-Der** [comment]
Hi @spkpal 

What are you trying to do? What have you tried so far?

**Comment by spkpal** [comment]
Hey Sean

when i try to download the custom OBS from here, it keeps on getting blocked my norton anti-virus program

when i try to out broadcast box on here

how can i stop that from happening

thanks

**Comment by otterpro** [comment]
I think you are downloading the OBS from a wrong source (possibly a fake OBS?).  Did you try building the OBS locally?

**Comment by Sean-Der** [comment]
Hi @spkpal can you link where you downloaded OBS from?

a official release should be available soon also.

**Comment by Sean-Der** [comment]
Hi @spkpal if you are still having issues please re-open!

Hopefully everything is working for you and you are enjoying OBS and WebRTC :D
