### ISSUE TITLE
new clients cannot load video after a random amount of time unless source reconnects.

### ISSUE THREAD

**Issue by jfarre20** [Glimesh/broadcast-box#23]
I run a 24/7 test stream at [https://testrp.cdtv.live/smashbets](https://testrp.cdtv.live/smashbets)

I find that after a random amount of time, (sometimes as short as a few minutes). no new users can connect to the stream.
If you are already watching, it continues working - but open another tab or refresh and it wont load unless I stop/start OBS's streaming output.

**Comment by Sean-Der** [comment]
Hey @jfarre20! 

Sorry about that. Would you mind capturing a `chrome://webrtc-internals` dump on a client that isn't able to connect?

**Comment by jfarre20** [comment]
I forgot to update my issue, I updated my docker container to your latest
commit and it's been behaving so far. however if it does act up I will do
this.

**Comment by Sean-Der** [comment]
That's great news! Glad it is working for you @jfarre20 

I am available in https://pion.ly/slack if you ever want to debug right away.
