### ISSUE TITLE
Remove / Update "Peer-to-Peer (if you need it)" section on Readme

### ISSUE THREAD

**Issue by Wowol** [Glimesh/broadcast-box#24]
Broadcast-box does not create direct connections between two peers on its own.

In the README, it is stated:
```
With Broadcast Box you can serve your video without a public IP or forwarding ports!
```

However, this claim is not accurate - we still need to establish connection between peers somehow, and definetely broadcast-box cannot do this for us since we may be limited by NAT - so we may need to have public IP or forwarding ports (we have p2p transmission, not discovery).

**Comment by Sean-Der** [comment]
@Wowol 

Broadcast Box can operate behind a NAT. Populate the `webrtc.Configuration` with a STUN/TURN server [here](https://github.com/Glimesh/broadcast-box/blob/main/internal/webrtc/whep.go#L88) and it will attempt to create a NAT Hole Punch.

I do this today + use ngrok. I publish OBS -> Broadcast Box. I use Twillio STUN and make Broadcast Box HTML available via ngrok.

----

I think it is worth adjusting the README to explain this more. I don't want to remove it entirely though. I think this could be a big advantage to users who are only aware of RTMP+HLS.

**Comment by Wowol** [comment]
Sounds good - explaining in README how to configure third party STUN/TURN server would be very useful.

Thanks!
