### ISSUE TITLE
WHIP Handler should return Location header

### ISSUE THREAD

**Issue by colemickens** [Glimesh/broadcast-box#25]
If this is added, gstreamer can publish to broadcast-box.

**Comment by Sean-Der** [comment]
Would love that! Interested in implementing @colemickens ?

**Comment by colemickens** [comment]
#26 adds one line of Go to make gstreamer happy, and then many more for a 2-in-1 example and usage and callout in the README.

**Comment by Sean-Der** [comment]
Not familiar with nu scripts, very cool!

I will update docker image tonight
