### ISSUE TITLE
No idea what "Publish Stream" does

### ISSUE THREAD

**Issue by colemickens** [Glimesh/broadcast-box#31]
Sorry if I'm just being kind of dumb, but I can't figure out what the "Publish" feature is supposed to be?

I figured maybe it was to broadcast a webcam/screen share from the browser? Maybe it's just not working for me?

**Comment by Chat-mots** [comment]
@colemickens The publish feature is for broadcasting your camera and microphone. It's a bit confusing at first I agree. When you publish your webcam at `http://mybroadcastbox.box/publish/mykey`, people can see you if they go to `http://mybroadcastbox/mykey`. You're publishing with the `mykey` key.

I think a message once you start broadcasting saying "LIVE : Currently streaming your camera and microphone to `http://mybroadcast.box/mykey` would help.

**Comment by Sean-Der** [comment]
That’s a cool idea @Chat-mots!

you should implement! I would love to help if you have any questions

**Comment by Chat-mots** [comment]
@Sean-Der I'll try ! I wanted to do this but I've almost never used javascript and I need to figure how it works before I can push any thing :)

**Comment by colemickens** [comment]
Maybe my confusion is simply stemming from the fact that I don't have a webcam, and the page sorta doesn't specially handle that case? For me, when I go to the publish page, I get a blank video player...

![screenshot-1692582125](https://github.com/Glimesh/broadcast-box/assets/327028/ab2e3072-21bc-44b2-8d6d-875ebbe77b95)

**Comment by makindotcc** [comment]
> Maybe my confusion is simply stemming from the fact that I don't have a webcam, and the page sorta doesn't specially handle that case? For me, when I go to the publish page, I get a blank video player...


Exactly, that is the case. I've tested now on my macbook with restricted camera access for chrome on macOS level
![broadcast box screenshot with devtools showing "DOMException: Requested device not found"](https://github.com/Glimesh/broadcast-box/assets/9150636/16d1fe73-95ad-430e-b999-1ed716d31c82)

We should handle exceptions here:
https://github.com/Glimesh/broadcast-box/blob/51c0655751995ab790bd6778ccc4a2a855f49916/web/src/components/publish/index.js#L12
specified at https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia

**Comment by Sean-Der** [comment]
Any luck with this @colemickens ?
