### ISSUE TITLE
Publish Stream: support publishing a screenshare session instead of webcam?

### ISSUE THREAD

**Issue by colemickens** [Glimesh/broadcast-box#32]
Just an idea on the back of #31. It seems like it would be in the spirit of the application to support broadcasting a getUserMedia thingy as an alternative to a webcam?

**Comment by Sean-Der** [comment]
@colemickens That sounds great!

Replace `getUserMedia` with `getDisplayMedia`. It would be nice to keep things low friction.

Maybe we do `getUserMedia` by default. We also provide a button that you can press to switch to `getDisplayMedia` instead?

**Comment by heinrich5991** [comment]
> Replace `getUserMedia` with `getDisplayMedia`. It would be nice to keep things low friction.
> 
> Maybe we do `getUserMedia` by default. We also provide a button that you can press to switch to `getDisplayMedia` instead?

That doesn't seem to work, it displays a red bar at the top:

> Could not access your media device:
InvalidStateError: getDisplayMedia requires transient activation from a user gesture.

**Comment by Sean-Der** [comment]
Hey @colemickens @heinrich5991 

I added rough support for this. It requires that the source does Audio+Video (so display captures on MacOS does not work yet).

Tab capture works great though! I will finish the server generating silent audio tomorrow.

**Comment by Sean-Der** [comment]
This has been fully implemented @colemickens and @heinrich5991 

Hopefully it works for your needs! If you have any feedback I would love to hear :)
