### ISSUE TITLE
Recent commits cause can't bind address with udp mux port

### ISSUE THREAD

**Issue by Gol-D-Ace** [Glimesh/broadcast-box#35]
Hi

Tried this on a VM with bridged network behind a IPv4 NAT running on Ubuntu 23.04

Checking out the latest commit causes an address bind error saying the address is already bound.

Checking out e6f7b56 resolves the issue.

**Comment by Sean-Der** [comment]
That's my mistake, sorry about that @Gol-D-Ace !

I will have this fixed tonight

**Comment by Sean-Der** [comment]
Hey @Gol-D-Ace @jfarre20 mind trying again?

Sorry about the breakage, thanks for using Broadcast Box :)

**Comment by Gol-D-Ace** [comment]
Working now. Thank you very much.
