### ISSUE TITLE
How should I do peer-to-peer connection via broadcast-box

### ISSUE THREAD

**Issue by littleq0903** [Glimesh/broadcast-box#36]
In the readme:

"With Broadcast Box you can serve your video without a public IP or forwarding ports! Run Broadcast Box on the same machine that you are running OBS, and share your video with the world! WebRTC comes with P2P technology, so users can broadcast and playback video without paying for dedicated servers.

You could also use P2P to pull other broadcasters into your stream. No special configuration or servers required anymore to get sub-second costreams."

How should I set this up? if I set up a broadcast-box on a machine with a private ip, in another machine not in the same LAN (private ip) how should I point the WHEP location?

Thanks in advance.

**Comment by littleq0903** [comment]
```golang
webrtc.NewPeerConnection(webrtc.Configuration{
		ICEServers: []webrtc.ICEServer{
			{
				URLs: []string{"stun:stun.l.google.com:19302"},
			},
		},
	})
```

**Comment by littleq0903** [comment]
#24

**Comment by petrmalkov** [comment]
> ```go
> webrtc.NewPeerConnection(webrtc.Configuration{
> 		ICEServers: []webrtc.ICEServer{
> 			{
> 				URLs: []string{"stun:stun.l.google.com:19302"},
> 			},
> 		},
> 	})
> ```

Is it a kind of a public server to publish through?
How to pass this parameter into docker?

**Comment by Sean-Der** [comment]
Hi @littleq0903 @petrmalkov 

I added support for this! ICE Server for server can be set via env variable

 STUN_SERVERS allows users to pass a list of STUN servers. They are
 seperated by a '|'. Only the URL is required. The following is an
 example.

    export STUN_SERVERS='stun.l.google.com:19302|stun1.l.google.com:19302'

**Comment by lpapadakos** [comment]
Sorry for asking here, but I don't know what do do with this. How would a watcher connect to me, the streamer, in this case?

normally you'd do <my_ip>:<broadcast-box-port>/<streamkey> but without me port forwarding, you can't do that. how does a stun server help?

**Comment by Sean-Der** [comment]
@lpapadakos Please ask away! I am always happy when people use it :)

If you can port forward that would be best! The P2P makes sense if you do something like ngrok. You make the HTTP available over that (which bootstraps the WebRTC session)

The media itself will find a alternative P2P path. So it doesn't go over the slow/metered ngrok path.
