### ISSUE TITLE
Deployed broadcast-box to GCP but it seems not working like demo site

### ISSUE THREAD

**Issue by littleq0903** [Glimesh/broadcast-box#37]
I created the SSL certificate and modified main.go to adapt it, but it was not working even before the modification.

my webrtc-internals

![image](https://github.com/Glimesh/broadcast-box/assets/374786/0c60aaa4-0d62-4325-89ff-9ad2c9e65274)

I ran with port 443 and with port forwarding 80 -> 443, APP_ENV=production

is there any setup that readme didn't mention?

**Comment by littleq0903** [comment]
https://*****/publish/test, { iceServers: [], iceTransportPolicy: all, bundlePolicy: balanced, rtcpMuxPolicy: require, iceCandidatePoolSize: 0 }

ICE connection state: new => checking
Connection state: new => connecting
Signaling state: new => have-local-offer => stable
ICE Candidate pair:

**Comment by littleq0903** [comment]
I did this `docker run --rm -e UDP_MUX_PORT=8080 -e NAT_1_TO_1_IP=127.0.0.1 -p 8080:8080 -p 8080:8080/udp seaduboi/
broadcast-box` in my local machine, it doesn't work as well, and this looks like different version than the main branch, but looks like b.siobud.com version

**Comment by littleq0903** [comment]
Never mind, I resovled it, somehow on my google cloud the server tag didn't apply so udp on all ports are blocked.

**Comment by Sean-Der** [comment]
Glad you got it working! I idle on [Slack](https://pion.ly/slack) and able to help faster there :)
