### ISSUE TITLE
"Failed to connect" when trying to stream

### ISSUE THREAD

**Issue by A-tG** [Glimesh/broadcast-box#45]
When I try to stream without VPN to https://b.siobud.com/api/whip it fails to connect.
![image](https://github.com/Glimesh/broadcast-box/assets/19589064/1d99afc2-4447-4c43-b797-dbf02c362c55)

Log file
```
20:47:09.437: [obs-webrtc] [whip_output: 'adv_stream'] PeerConnection state is now: Connecting
20:47:09.970: ==== Streaming Start ===============================================
20:47:42.275: [obs-webrtc] [whip_output: 'adv_stream'] PeerConnection state is now: Failed
20:47:42.275: Output 'adv_stream': stopping
20:47:42.275: Output 'adv_stream': Total frames output: 966
20:47:42.275: Output 'adv_stream': Total drawn frames: 985
20:47:42.276: [obs-webrtc] [whip_output: 'adv_stream'] PeerConnection state is now: Closed
20:47:42.277: ==== Streaming Stop ================================================
```

**Comment by Sean-Der** [comment]
Hi @A-tG 

Can you try running locally? Russian networks have been blocking Pion because of Snowflake. https://www.wired.com/story/tor-browser-russia-blocks/

If it still doesn't work for you I would love to help! Sorry for the delay in my response
