### ISSUE TITLE
(Need Reproduce) Unable to watch stream when streaming for a while

### ISSUE THREAD

**Issue by RedMser** [Glimesh/broadcast-box#46]
Hey, thanks a lot for your work on this project! We're working through some of its kinks, but are kind of stumped on this one:

- Watching a stream over the internet works fine initially. We are self-hosting.
- But after the stream has been running for a minute or so, new users can no longer start watching the stream
  - According to the WebRTC debugger, packets are seemingly being exchanged, but the video just keeps on loading forever (stuck on black screen / loading spinner)
- But users that have already started watching the stream continue seeing it without problems

This only happens for one specific user, so it's likely a network configuration/stability problem of some kind.

We tried streaming with the newly released OBS 30, but it also happens via `/publish`.

Does anyone have any idea how to better debug this issue, or fix it?

**Comment by Sean-Der** [comment]
Is this still happening @RedMser?

I would love to help debug. Can you start a thread in https://discord.gg/An5jjhNUE3 and we can find a time to debug together?

**Comment by RedMser** [comment]
We have not retried since, but once I have a bit more time available (likely at the end of the month), I'll see if we can still reproduce on both self-hosted, and on the official instance.
If it's still a problem, then I'd be very thankful for your help debugging it!

**Comment by Sean-Der** [comment]
I am going to resolve. I haven't seen this myself, hopefully it is fixed :)

In the future if anyone hits this checkout out the `/api/status` it tells you the amount of packets flowing in+out and can be useful for debugging.
