### ISSUE TITLE
Errors on npm start. Dependencies mismatch?

### ISSUE THREAD

**Issue by Dogway** [Glimesh/broadcast-box#48]
Followed the guide but got issues on the last part.

- Installed Node.js for Windows, then Go
- Following on the web folder run `npm install`  (warns me about some deprecated critical packages)
- Back on the root folder run `go run .`
- On the web folder run `npm start`, and I get this:

```

D:\Portable Apps\broadcast-box\web>npm start

> broadcast-box@0.1.0 start
> dotenv -e ../.env.development react-scripts start

Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
(node:13972) [DEP_WEBPACK_DEV_SERVER_ON_AFTER_SETUP_MIDDLEWARE] DeprecationWarning: 'onAfterSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:13972) [DEP_WEBPACK_DEV_SERVER_ON_BEFORE_SETUP_MIDDLEWARE] DeprecationWarning: 'onBeforeSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
Starting the development server...
Compiled with warnings.

[eslint]
src\App.js
  Line 1:17:  'useContext' is defined but never used         no-unused-vars
  Line 6:22:  'CinemaModeContext' is defined but never used  no-unused-vars

src\components\header\index.js
  Line 6:9:  'navigate' is assigned a value but never used  no-unused-vars

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

WARNING in [eslint]
src\App.js
  Line 1:17:  'useContext' is defined but never used         no-unused-vars
  Line 6:22:  'CinemaModeContext' is defined but never used  no-unused-vars

src\components\header\index.js
  Line 6:9:  'navigate' is assigned a value but never used  no-unused-vars

webpack compiled with 1 warning

```

My goal is to broadcast to a class using WLAN, and encode at the same time so they have a repository to rewatch the class.
Also no `WebRTC` option in latest OBS Studio (v30.0.0)? Should I use WHIP instead?

**Comment by Sean-Der** [comment]
Hi @Dogway! Sorry I didn't get to this sooner. I fixed those eslint errors. I am also going to add something to Github Actions to make sure that doesn't happen again.

You did everything right. When you opened `http://localhost:3000` did you see Broadcast Box? Were you able to point OBS at it?

I am going to close hoping that everything worked :) If not please re-open or join the discord to debug together https://discord.gg/An5jjhNUE3

**Comment by Dogway** [comment]
Thanks, I will check this on Monday on the office and let you know then.

**Comment by Dogway** [comment]
Yes, it worked now locally. Didn't test on a local network yet, maybe for a classroom I'd need to stream to internet though.

**Comment by Sean-Der** [comment]
Great to hear @Dogway !

the second you hit issues reach out, I am here to help

**Comment by Dogway** [comment]
Ok, I tested over LAN from Laptop to my Desktop, and also over WAN from Laptop to the smartphone. Both had the same error.

- In OBS I set the server as http://localhost:8080/api/whip
- Stream Key as StreamTest and start streaming
- In a browser on the network's guest PC I access broadcast box through the IP given by "npm start", like: http://192.168.60.114:3000

It actually shows broadcast box panel but when I input the key and click Watch, this is the error I get in both cases (LAN and WAN)

![npm](https://github.com/Glimesh/broadcast-box/assets/13509598/dd373c9c-6d03-4ad1-829b-e2092e69600f)
![error](https://github.com/Glimesh/broadcast-box/assets/13509598/a3bf8ee7-d444-4662-9428-8c148ce3dcff)
