### ISSUE TITLE
Publish Pre-built OBS Images

### ISSUE THREAD

**Issue by clone1018** [Glimesh/broadcast-box#5]
Due to the WebRTC plugin not being available in OBS yet, we'll need to publish and maintain a small set of test images people can use to run OBS with WebRTC support.

Ideal platforms: Windows x64, Linux x64, MacOS x64 / ARM

Advanced code signing is required on Windows & Mac, however since we can't do that for OBS, we'll just need to have good instructions for the user on bypassing those installation requirements.

**Comment by mpisat** [comment]
I still can't find WHIP support in OBS, where do we get precompiled binaries?

**Comment by rhetr** [comment]
@mpisat you can track the progress of the PR [here](https://github.com/obsproject/obs-studio/pull/7926)
