### ISSUE TITLE
Public use of the status page

### ISSUE THREAD

**Issue by ChaseCares** [Glimesh/broadcast-box#55]
Hello, I have a few questions about the status page.

Are there any plans to disable the status page?
Is it acceptable to regularly pull the status page to monitor for new streams?
If yes, is there preferred frequency?

Would the project be open to a PR that would add a  `isActive`  key that would indicate if the stream key is in use?
 
I made a simple python script that checks the status page every ~5 minutes to look for new streams, and it has been quite entertaining. I've seen many interesting game streams, security cams and many people testing they are streaming setups, it's quite random and reminds me of the early days of Twitch.

I would like to create a simple script that will send a discord notification when a new stream is active, without being a burden on the system.

Thanks!
Chase

**Comment by Sean-Der** [comment]
Go for it! Build some cool hacks :)

https://b.siobud.com is a public resource. I plan to run it as long as it doesn't cause problems!

Would you be interested in running your script in the 'Real-time Broadcasting' discord? Would enjoy watching it myself :)
