### ISSUE TITLE
Unable to watch streams with self-hosted broadcast-box outside of LAN

### ISSUE THREAD

**Issue by DatCaptainHorse** [Glimesh/broadcast-box#8]
Heyo! I've been testing this along with the WebRTC PR for OBS-Studio, it's working amazingly except for one issue.

I am unable to see streams from my hosted broadcast-box outside of LAN (https://live.dathorse.com/), while siobud site works fine.
Using `-e INCLUDE_PUBLIC_IP_IN_NAT_1_TO_1_IP=yes` with `--net=host` hasn't worked, in fact using that environment variable causes OBS-Studio to freeze from an error (if needed, can provide).

Not sure if this is relevant issue for the project?

**Comment by DatCaptainHorse** [comment]
Closing as I've learned since posting this, that ICE servers are required in order to watch outside of LAN.

**Comment by docbray** [comment]
Hello! Wanted to see if getting ICE servers implemented on your box was able to resolve the problem for you?

**Comment by DatCaptainHorse** [comment]
> Hello! Wanted to see if getting ICE servers implemented on your box was able to resolve the problem for you?

Yeah, I think I needed to add "stun:stun.l.google.com:19302" to the client side ICE server list? It's been a while, but guessing that was it.
