### ISSUE TITLE
Failed to compile with npm build

### ISSUE THREAD

**Issue by mpisat** [Glimesh/broadcast-box#9]
root@localhost:~/src/broadcast-box/web# npm run build

> broadcast-box@0.1.0 build
> dotenv -e ../.env.production react-scripts build

Creating an optimized production build...
Failed to compile.

./src/components/header/index.js
  Line 7:    'React' must be in scope when using JSX  react/react-in-jsx-scope
  Line 8:    'React' must be in scope when using JSX  react/react-in-jsx-scope
  Line 9:    'React' must be in scope when using JSX  react/react-in-jsx-scope
  Line 10:  'React' must be in scope when using JSX  react/react-in-jsx-scope
  Line 11:  'React' must be in scope when using JSX  react/react-in-jsx-scope
  Line 15:  'React' must be in scope when using JSX  react/react-in-jsx-scope
  Line 16:  'React' must be in scope when using JSX  react/react-in-jsx-scope
  Line 17:  'React' must be in scope when using JSX  react/react-in-jsx-scope
  Line 18:  'React' must be in scope when using JSX  react/react-in-jsx-scope
  Line 30:   'React' must be in scope when using JSX  react/react-in-jsx-scope
  Line 31:   'React' must be in scope when using JSX  react/react-in-jsx-scope
  Line 32:  'React' must be in scope when using JSX  react/react-in-jsx-scope
  Line 36:   'React' must be in scope when using JSX  react/react-in-jsx-scope
  Line 37:   'React' must be in scope when using JSX  react/react-in-jsx-scope
  Line 38:  'React' must be in scope when using JSX  react/react-in-jsx-scope
  Line 39:  'React' must be in scope when using JSX  react/react-in-jsx-scope
  Line 41:  'React' must be in scope when using JSX  react/react-in-jsx-scope
  Line 42:  'React' must be in scope when using JSX  react/react-in-jsx-scope
  Line 44:  'React' must be in scope when using JSX  react/react-in-jsx-scope
  Line 45:  'React' must be in scope when using JSX  react/react-in-jsx-scope

Search for the keywords to learn more about each error.

**Solution:**
add the following line to ./src/components/header/index.js
`import React from 'react'`

root@localhost:~/src/broadcast-box/web# nano ./src/components/header/index.js
root@localhost:~/src/broadcast-box/web# npm run build

> broadcast-box@0.1.0 build
> dotenv -e ../.env.production react-scripts build

Creating an optimized production build...
Compiled successfully.

File sizes after gzip:

  63.29 KB  build/static/js/1.9791ad40.chunk.js
  1.55 KB   build/static/js/main.6ba1d3d7.chunk.js
  763 B     build/static/js/runtime~main.229c360f.js
  297 B     build/static/css/main.36234f33.chunk.css

The project was built assuming it is hosted at the server root.
You can control this with the homepage field in your package.json.
For example, add this to build it for GitHub Pages:

  "homepage" : "http://myname.github.io/myapp",

The build folder is ready to be deployed.
You may serve it with a static server:

  npm install -g serve
  serve -s build

Find out more about deployment here:

  https://bit.ly/CRA-deploy

However, I still get a weird looking page (No css?)

**Comment by mpisat** [comment]
I copied compiled css from https://b.siobud.com/ and it looks pretty good now. It's a great tech demo.

**Comment by clone1018** [comment]
Hi good morning @mpisat -- can you ruin `node --version` and `npm --version` for me?

**Comment by mpisat** [comment]
> Hi good morning @mpisat -- can you ruin `node --version` and `npm --version` for me?

root@localhost:~# node --version
v14.21.1
root@localhost:~# npm --version
9.3.1

**Comment by Sean-Der** [comment]
Hi @mpisat 

Anything else that would make it an even better tech demo? I have some time to spend on it again in the next few weeks!

Sorry we never got this resolved. I haven't been able to reproduce your issue myself :/
I am going to resolve. If you are still having problems please reach out! Thanks for using broadcast-box

**Comment by mpisat** [comment]
Latest code builds just fine, I've tested it
