### ISSUE TITLE
Where's the discord?

### ISSUE THREAD

**Issue by pato-pan** [Glimesh/broadcast-box#95]
It's mentioned in the readme, but it's not linked anywhere. I have a problem with the video not being shown when I selfhost (built from source) and watch the stream, I only receive audio, I use OBS to stream

**Comment by ChaseCares** [comment]
Sorry you're having issues! Here's the link to the discord https://discord.gg/YMRrkQnb, one issue with discord invite links as they expire relatively quickly.

Do you have the same issue when you broadcast to https://b.siobud.com?

**Comment by pato-pan** [comment]
no, only when I self-host

I also built from source, I can't use docker because last time I had it installed and I updated my system linux-vmz just noped out of nowhere for no reason.

Is there any chance you can create a permanent discord link to add to the readme?

**Comment by pato-pan** [comment]
I made one https://discord.com/invite/DvQz8vSvg6

I hope that's okay

**Comment by Sean-Der** [comment]
Sorry about that @pato-pan!

If you click the discord badge it is a link. I also updated the 'Join the discord' to be a link.

My guess is that the self host box is constrained in some way (network/cpu/?) if that is the only variable!

**Comment by pato-pan** [comment]
> Sorry about that @pato-pan!
> 
> If you click the discord badge it is a link. I also updated the 'Join the discord' to be a link.
> 
> My guess is that the self host box is constrained in some way (network/cpu/?) if that is the only variable!

Hey good news, I figured it out!

It works on Firefox, but not Waterfox. I am not sure why, I tried to find the setting that didn't allow it to work, but couldn't find it and I don't want to spend more time trying to find it.

Thanks for the update.

**Comment by pato-pan** [comment]
the h264 plugin is not installed, that's why it's happening
